linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
run:
  timeout: 5m

issues:
  exclude-rules:
    - linters:
        - govet
      text: "could not import C"

linters-settings:
  golint:
    min-confidence: 0.8

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/ytka/ai-text-shaper

