linters-settings:
  goimports:
    local-prefixes: github/ytka/ai-text-shaper
linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
run:
  timeout: 5m
