version: '3'


tasks:
  # build the project
  build:
    desc: Build the project
    vars:
      Version:
        sh: git describe --abbrev=0 --tags
      Commit:
        sh: git rev-list -1 HEAD
      Date:
        sh: date -u '+%Y-%m-%d_%I:%M:%S%p'
    cmds:
      - go build -ldflags="-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=local-build"
  install:
    desc: Install dependencies
    deps: [build]
    cmds:
      - cp ./textforge ~/bin/
  # dependencies
  tidy:
    desc: Tidy the project
    cmds:
      - go mod tidy
  # static analysis
  lint:
    desc: Lint the project
    cmds:
      - golangci-lint run
  lint-fix:
    desc: Fix lint errors
    cmds:
      - golangci-lint run --fix
  lint-fix-forge:
    desc: Fix lint errors
    cmds:
       - golangci-lint run > /tmp/lint.txt || true
       - cat /tmp/lint.txt
       - |
         files=$(cat /tmp/lint.txt | awk -F: '/.go:/ {print $1}' | sort | uniq) && cat /tmp/lint.txt | go run main.go --rewrite -P=prompts/ja/go/fix-lint-error.txt $files
  import-fix:
    desc: Fix import errors
    cmds:
      - goimports -w -local github.com/ytka/textforge .
  # forge development
  auto-review-changed:
    desc: Review the project
    cmds:
      - |
        changed=$(git diff --name-only @{push} | grep -E '.go$|.yaml|.yml|.md' | tr '\n' ' ') && go run main.go --rewrite -p="以下のファイルをレビューし、重要な問題があれば修正して。" $changed
  auto-review:
    desc: Review the project
    cmds:
      - |
        shopt -s globstar      
        go run main.go --rewrite -P=prompts/ja/go/review-fix.txt **/*.go
  auto-commit:
    desc: Commit changes to the repository
    cmds:
      - git diff | go run main.go -P=prompts/en/commit-msg.txt -c -f --outpath=/tmp/commit-msg && git add . && git commit -m "$(cat /tmp/commit-msg)" || echo "Abort"
  # forge documentation
  forge-doc-by-help:
    desc: Forge the documentation
    cmds:
      - printf "以下のプログラムのヘルプに基づいて READMEを更新して。\n%s" "$(go run main.go --help)" | go run main.go -P - README.ja.md --rewrite --show-cost
  forge-doc-by-taskfile:
    desc: Forge the documentation
    cmds:
      - printf "以下のプログラムの利用例に基づいて READMEの使い方や利用例を更新して。\n%s" "$(cat Taskfile.yaml)" | go run main.go -P - README.ja.md --rewrite --show-cost
  translate-prompts-to-en:
    desc: Translate the commit message to English
    cmds:
      - rm -rf prompts/en/
      - mkdir -p prompts/en
      - cp -rf prompts/ja/* prompts/en/
      - |
        shopt -s globstar
        for file in prompts/en/**/*.txt; do
          echo translate: $file
          go run main.go -p "Translate to English." $file --rewrite
        done
  translate-readme-to-en:
    cmds:
      - go run main.go -p "Translate to English." README.ja.md --outpath README.md
  # other
  dl-source:
    cmds:
      - curl -L -O https://github.com/ytka/textforge/archive/main.zip
