version: '3'

tasks:
  build:
    desc: Build the project
    vars:
      Version:
        sh: git describe --abbrev=0 --tags
      Commit:
        sh: git rev-list -1 HEAD
      Date:
        sh: date -u '+%Y-%m-%d_%I:%M:%S%p'
    cmds:
      - go build -ldflags="-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=local-build"
  install:
    desc: Install dependencies
    deps: [build]
    cmds:
      - cp ./ai-text-shaper ~/bin/
  dl-source:
    curl -L -O https://github.com/ytka/ai-text-shaper/archive/main.zip
  translate-prompts-to-en:
    desc: Translate the commit message to English
    cmds:
      - rm -rf prompts/en/
      - mkdir -p prompts/en
      - cp -rf prompts/ja/* prompts/en/
      - |
        shopt -s globstar
        for file in prompts/en/**/*.txt; do
          echo translate: $file
          go run main.go -p "Translate to English." $file --rewrite
        done
  translate-readme-to-en:
      - go run main.go -p "Translate to English." README.ja.md --outpath README.md
  commit-msg:
    desc: Generate a commit message
    cmds:
      - git diff | go run main.go -P=prompts/en/commit-msg.txt
  auto-commit:
    desc: Commit changes to the repository
    cmds:
      - git add .
      - git diff --cached | go run main.go -P=prompts/en/commit-msg.txt | git commit -F -
  auto-commit-cached:
    desc: Commit changes to the repository
    cmds:
      - git diff --cached | go run main.go -P=prompts/en/commit-msg.txt | git commit -F -