version: '3'

tasks:
  tidy:
    desc: Tidy the project
    cmds:
      - go mod tidy
  lint:
    desc: Lint the project
    cmds:
      - golangci-lint run
  lint-fix:
    desc: Fix lint errors
    cmds:
      - golangci-lint run --fix
  lint-fix-ai:
    desc: Fix lint errors
    cmds:
       - golangci-lint run > /tmp/lint.txt || true
       - echo /tmp/lint.txt
       - |
         files=$(cat /tmp/lint.txt | awk -F: '/.go:/ {print $1}' | sort | uniq) && cat /tmp/lint.txt | go run main.go --rewrite -P=/tmp/prompt.txt $files
  import-fix:
    desc: Fix import errors
    cmds:
      - goimports -w -local github/ytka/ai-text-shaper .
  build:
    desc: Build the project
    vars:
      Version:
        sh: git describe --abbrev=0 --tags
      Commit:
        sh: git rev-list -1 HEAD
      Date:
        sh: date -u '+%Y-%m-%d_%I:%M:%S%p'
    cmds:
      - go build -ldflags="-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=local-build"
  install:
    desc: Install dependencies
    deps: [build]
    cmds:
      - cp ./ai-text-shaper ~/bin/
  dl-source:
    curl -L -O https://github.com/ytka/ai-text-shaper/archive/main.zip
  translate-prompts-to-en:
    desc: Translate the commit message to English
    cmds:
      - rm -rf prompts/en/
      - mkdir -p prompts/en
      - cp -rf prompts/ja/* prompts/en/
      - |
        shopt -s globstar
        for file in prompts/en/**/*.txt; do
          echo translate: $file
          go run main.go -p "Translate to English." $file --rewrite
        done
  translate-readme-to-en:
      - go run main.go -p "Translate to English." README.ja.md --outpath README.md
  ai-fix-code:
    desc: Fix code with AI
    cmds:
      - |
        shopt -s globstar      
        go run main.go --rewrite -P=prompts/ja/fix-go.txt **/*.go
  ai-fix-code-dry:
    desc: Fix code with AI
    cmds:
      - |
        shopt -s globstar      
        go run main.go --dry-run --rewrite -P=prompts/ja/fix-go.txt **/*.go
  auto-commit:
    desc: Commit changes to the repository
    cmds:
      - git diff | go run main.go -P=prompts/en/commit-msg.txt -c -f --outpath=/tmp/commit-msg && git add . && git commit -m "$(cat /tmp/commit-msg)" || echo "Abort"
