version: '3'

tasks:
  to-ja:
    desc: Translate the commit message to Japanese
    cmds:
      - go run main.go -P=prompts/to-ja README.md --outpath README.ja.md
  commit-msg:
    desc: Generate a commit message
    cmds:
      - git diff | go run main.go -P=prompts/commit-msg.txt
  auto-commit:
    desc: Commit changes to the repository
    cmds:
      - git add .
      - git diff --cached | go run main.go -P=prompts/commit-msg.txt | git commit -F -
  auto-commit-cached:
    desc: Commit changes to the repository
    cmds:
      - git diff --cached | go run main.go -P=prompts/commit-msg.txt | git commit -F -